name: deploy on rancher
on:
  workflow_dispatch: ~
  release:
    types: [published]
env:
  RANCHER_API_BASE: https://rancher.acdh-dev.oeaw.ac.at/v3
  RANCHER_PROJECT: Dissemination services
  RANCHER_NAMESPACE: arche-thumbnails
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: test
      #  run: |
      #    composer update
      #    vendor/bin/phpunit tests
      - name: build docker image
        run: |
          git reset --hard HEAD
          rm -fR vendor
          mkdir build/docroot && cp -R `ls -1 | grep -v ^build` build/docroot/ && cp build/config/arche.yaml build/docroot/config.yaml && cp -R build/assets/arche build/docroot/assets && mkdir build/docroot/cache && mkdir build/docroot/tmp && cp .htaccess build/docroot/
          docker build --rm -t "acdhch/$RANCHER_NAMESPACE:latest" --build-arg VARIANT=production --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" build
      - name: test image
        run: |
          docker run -d --name "$RANCHER_NAMESPACE" -p 8080:80 "acdhch/$RANCHER_NAMESPACE:latest"
          sleep 1
          # separate title image - Image class
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms?width=150'
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms?width=150'
          # collection - Fallback class
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/editions?width=150'
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/editions?width=150'
          # text file - Text class
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/t__01_VMS_1854_TEI_AW_26-01-21-TEI-P5.xml?width=150'
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/t__01_VMS_1854_TEI_AW_26-01-21-TEI-P5.xml?width=150'
          # image - Image class
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/vms_1854_002.tif'
          curl -f -i 'http://127.0.0.1:8080/id.acdh.oeaw.ac.at/hanslick-vms/vms_1854_002.tif'
      - name: authorize against docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push "acdhch/$RANCHER_NAMESPACE:latest"
      - name: redeploy on rancher
        run: |
          BASE_URL=`curl -s -H "Authorization: Bearer ${{ secrets.RANCHERTOKEN }}" "$RANCHER_API_BASE/projects" | jq -r ".data[] | select(.name == \"$RANCHER_PROJECT\") | .links.workloads"`
          curl -i -X POST -H "Authorization: Bearer ${{ secrets.RANCHERTOKEN }}" "$BASE_URL/deployment:$RANCHER_NAMESPACE:$RANCHER_NAMESPACE?action=redeploy"

